### ISSUE TITLE
Validate run params hyperparameters for convergence

### ISSUE THREAD

**Issue by cloderic** [cogment/cogment-verse#16]
## Objective

- Validate hyperparameters for the run params in the repository

Targeted environment are:
- Cartpole
- Pendulum
- Lunar Lander
- Lunar Lander Continuous
- One environment on MinAtar (Breakout)
- One environment on Atari (Breakout)
- Connect 4

**Comment by cloderic** [comment]
Also storing the results of the experiments somewhere in the repo would be nice

**Comment by saikrishna-1996** [comment]
covered in #76
