### ISSUE TITLE
Debug/Benchmark Async PPO implementation

### ISSUE THREAD

**Issue by cloderic** [cogment/cogment-verse#177]

**Comment by lhnguyen102** [comment]
Here is the performance of APPO on `hopper-v3`. You also can find the hopper benchmark in [1].
![reward_comp_hopper](https://github.com/cogment/cogment-verse/assets/28932460/d1dcb121-86cf-4d38-befc-ada652d6d306)


[1] Proximal Policy Optimization Algorithms [Schulman et al., 2017]](https://arxiv.org/pdf/1707.06347.pdf)
